### ISSUE TITLE
M3 Completion

### ISSUE THREAD

**Issue by noahstaz** [trevorwinser/Infinite-Loopers#102]
- [x] Updating the testing plan to better fit the project
- [x] Update the design patterns with diagrams 
- [x] Complete the sequence diagrams
- [ ] Submit M3

Complete all the above tasks so that we can submit the M3 document by the due date on Friday.

**Comment by komalsingh0925** [comment]
Within the next week, I will enhance our existing design patterns documentation by adding clear and detailed diagrams for each pattern described. This will involve creating or updating diagrams for a set number of design patterns, ensuring that each is accurately represented and understood. This update will make our documentation more accessible and useful for the development team, aiding in the correct application of these patterns in our projects.

**Comment by noahstaz** [comment]
I finished the testing plan with the feedback received from the TA in today's meeting

**Comment by noahstaz** [comment]
@komalsingh0925 submitted M3
