### ISSUE TITLE
Testing Automation selenium + SQLite

### ISSUE THREAD

**Issue by noahstaz** [trevorwinser/Infinite-Loopers#163]

**Comment by komalsingh0925** [comment]
Within one week, implement GitHub Actions to automate running unit tests, Selenium integration tests, and SQLite database tests on every pull request and push to the main branch, aiming for at least 80% code coverage. This goal will enhance our application's reliability by ensuring that all new changes are thoroughly tested before integration, thereby maintaining high code quality and functionality.

**Comment by noahstaz** [comment]
completed and implemented
