### ISSUE TITLE
Status of the software implementation

### ISSUE THREAD

**Issue by komalsingh0925** [trevorwinser/Infinite-Loopers#181]
- How many of your initial requirements that your team set out to deliver did you actually deliver (a checklist/table would help to summarize)?  Were you able to deliver everything or are there things missing?  Did your initial requirements sufficiently capture the details needed for the project?
- If you have any requirements unimplemented, you will want to include an extra section showing those requirements have not been implemented.
- If you have a requirement that is partially working but feel that there's enough you don't want to call the whole requirement as incomplete, then break it up into two requirements, with one shown as tested and working, while the other is shown as not working.
- How many tasks are left in the backlog?

**Comment by noahstaz** [comment]
Complete
