### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by noahstaz** [trevorwinser/Infinite-Loopers#53]
- [ ] Download VS Code
- [ ] Download Gitkracken or Github Desktop
- [ ] Connect Gitkraken or Github Desktop to github
- [ ] Clone Repository

#14

**Comment by noahstaz** [comment]
Done!

**Comment by komalsingh0925** [comment]
Done!

**Comment by julieflament** [comment]
done!

**Comment by noahstaz** [comment]
Everyone has done
