### ISSUE TITLE
Working Login

### ISSUE THREAD

**Issue by noahstaz** [trevorwinser/Infinite-Loopers#93]
- [x] Have the login work with a user in the in the database
#37 

- [x] Change the login and registration page to Flask format
- [x] Once logged in header will show the username under the user image, we want to be able to pull this variable on other pages so that we know which user is logged in

**Comment by noahstaz** [comment]
@danglakshay I added a requirement to this issue that I feel like was missing that can be looked into next sprint

**Comment by danglakshay** [comment]
Login Operational with #152
