### ISSUE TITLE
Visualization Exploration

### ISSUE THREAD

**Issue by noahstaz** [trevorwinser/Infinite-Loopers#98]
- [ ] Explore how to get the visualizations working
- [ ] Maybe Flask is involved
- [ ] Javascript libraries 

Within the next week, I will successfully implement the integration of Flask with HTML, CSS, and JavaScript to enable dynamic visualizations in the navigation bar, user dashboard, and admin dashboard of our web application. This will include documenting the process and demonstrating at least one interactive visualization per section, thereby enhancing the application's functionality and user interface.

 #32

**Comment by komalsingh0925** [comment]
Visualizations have been explored. Created visualization with hard coded data for now using charts.js. Will create dynamic visualizations next sprint.
